version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/drupal/Dockerfile
      args:
        - composer_arg=
    volumes:
      - ./data/test_output:/tmp/tests
    environment:
      - SIMPLETEST_DB=mysql://docker:docker@db/docker
      - SIMPLETEST_BASE_URL=http://localhost
      - BROWSERTEST_OUTPUT_DIRECTORY=/tmp/tests
      - SYMFONY_DEPRECATIONS_HELPER=weak
      - MINK_DRIVER_ARGS_WEBDRIVER='["chrome",{"chrome":{"switches":["disable-gpu","window-size=1280,1024"]}},"http://selenium:4444/wd/hub"]'
    depends_on:
      - db
      - solr
      - redis
      - selenium
  db:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
  solr:
    build:
      context: .
      dockerfile: docker/solr/Dockerfile
  redis:
    image: redis
  selenium:
    image: selenium/standalone-chrome:3.8.1-bohrium
    volumes:
      - /dev/shm:/dev/shm
