version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/drupal/Dockerfile
      args:
        - composer_arg=
    ports:
      - "8090:80"
    volumes:
      - ./data/drupal:/var/www/html
    depends_on:
      - db
      - solr
      - redis
  db:
    image: mariadb
    volumes:
      - ./data/dump:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
  solr:
    build:
      context: .
      dockerfile: docker/solr/Dockerfile
  redis:
    image: redis
